GithubApiProject/Models/ErrorViewModel.cs
using System;

namespace GithubApiProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GithubApiProject/Models/GithubRepo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GithubApiProject.Models
{
    public class GithubRepo
    {
        //This is your "data"
        //This repository can include whatever field we want to extract from the api calls
        public string Username { get; set; } //repo owner
        public string Name { get; set; } //repo name
        public string Html_url { get; set; } //url for the repo
    }
}

GithubApiProject/Models/GithubRepoDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GithubApiProject.Models
{
    public class GithubRepoDbContext : DbContext
    {
        //Every time you create a Db context class, you need an empty constructor
        //Since we are using Core, we need dependency injection
        //Which also will invoke base class constructor
        public GithubRepoDbContext(DbContextOptions<GithubRepoDbContext> options) : base(options)
        {

        }

        public DbSet<GithubRepo> GithubRepos { get; set; }
        public DbSet<UserRepository> UserRepositories { get; set; }
    }
}

GithubApiProject/Models/UserRepository.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace GithubApiProject.Models
{
    public class UserRepository
    {
        //Setting fk restraints
        //[ForeignKey("GithuRepo")]
        public string RepositoryName { get; set; } //name of repository

        //One repository can have one user
        //Using navigation property, virtual one
        public virtual GithubRepo GithubRepo { get; set; }
    }
}

GithubApiProject/Controllers/ErrorHandlerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GithubApiProject.Controllers
{
    [Route("Redirected")]
    public class ErrorHandlerController : Controller
    {
        [HttpGet]
        public IActionResult Error404()
        {
            return View();
        }
    }
}

GithubApiProject/Controllers/GithubRepoController.cs
using GithubApiProject.Models;
using GithubApiProject.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace GithubApiProject.Controllers
{
    public class GithubRepoController : Controller
    {
        private readonly IGithubApiService _githubApiService;

        //Constructor injection, IoC princip
        //DI type, constructor injection
        //GithubRepoController is the client class - IGithubApiService is the injector class that injects its service
        public GithubRepoController(IGithubApiService githubApiService)
        {
            _githubApiService = githubApiService;
        }

        // GET: GithubRepoController
        [HttpGet]
        [Route("githubrepo")]
        public IActionResult Index()
        {
            return View();
        }

        // GET: GithubRepoController/GetRepositoriesForSingleUser/{Username}
        [HttpGet]
        public async Task<IActionResult> GetRepositoriesForSingleUser(string Username)
        {
            IEnumerable<GithubRepo> result = await _githubApiService.GetRepositoriesForGivenUser(Username);
            ViewBag.Username = Username; //to retrieve the name of the inputted user
            //ViewBag.GithubRepo = result; //to be able to display data on page
            if(result.Count() > 0) //if we get repos back
                return View(result);
            else
                return RedirectToAction("Error404", "ErrorHandler", null);
        }
    }
}

GithubApiProject/Controllers/HomeController.cs
using GithubApiProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GithubApiProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GithubApiProject/Views/ErrorHandler/Error404.cshtml
@{
    ViewData["Title"] = "Error404";
}
<head>
    <link href="~/css/ErrorStyling.css" rel="stylesheet" />
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Arvo'>
</head>
<body>
    <section class="page_404">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 ">
                    <div class="col-sm-10 col-sm-offset-1  text-center">
                        <div class="four_zero_four_bg">
                            <h1 class="text-center ">404</h1>
                        </div>

                        <div class="contant_box_404">
                            <h3 class="h2">
                                Looks like the USER you have entered does not exist
                            </h3>

                            <p>OR the USER has no repositories as of now</p>

                            <a asp-controller="githubrepo" asp-action="Index" class="link_404">Go to Search</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

GithubApiProject/Views/GithubRepo/GetRepositoriesForSingleUser.cshtml
@model IEnumerable<GithubApiProject.Models.GithubRepo>

@{
    ViewData["Title"] = "GetRepositoriesForSingleUser";
}
<head>
    <link href="~/css/styling.css" rel="stylesheet" />
</head>
<h1>Repositories for your entered user: 
    @{
        string username = ViewBag.Username;
    }
    @username
</h1>
<body>
    <table>
        <thead>
            <tr>
                <th>Owner</th>
                <th>Project Name</th>
                <th>Path</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var repo in Model)
            {
                <tr>
                    <td>@username</td>
                    <td>@repo.Name</td>
                    <td><a href="@repo.Html_url">Link to Github Repository</a></td>
                </tr>
            }
        </tbody>
    </table>
</body>

GithubApiProject/Views/GithubRepo/Index.cshtml
@model GithubApiProject.Models.GithubRepo
@{
    ViewData["Title"] = "Index";
}

<!DOCTYPE html>
<html>
<body>
    <h2>Github Repositories Collector</h2>

    <form action="/">
        <p>Enter username:</p>
        <input type="text" asp-for="Username" required="required"><br>
        <button asp-controller="githubrepo" asp-action="GetRepositoriesForSingleUser" type="submit">
            Get Repositories
        </button>
    </form>
</body>
</html>

GithubApiProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GithubApiProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GithubApiProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GithubApiProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="GithubRepo" asp-action="Index">Search
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GithubApiProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>